# .circleci/config.yml
version: 2.1

import:
  - .circleci/jobs.yml

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - install_dependencies
      - build_application:
          requires:
            - install_dependencies
      - run_tests:
          requires:
            - build_application
      - deploy_application:
          requires:
            - run_tests

# CCIPAT_4LDDFW2P5cT7xnRv1obvjN_8b65e11115ff90b905335fa5e72836625f101a68