# .circleci/config.yml
version: 2.1

import:
  - ./jobs.yml

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - install_dependencies
      - build_application:
          requires:
            - install_dependencies
      - run_tests:
          requires:
            - build_application
      - deploy_application:
          requires:
            - run_tests
